### ISSUE TITLE
Maven repository is missing

### ISSUE THREAD

**Issue by maksimu** [spinscale/dropwizard-jobs#10]
I'm using dropwizard-jobs in my maven project. When maven is downloading this library from [Sonatype repository](http://oss.sonatype.org/content/repositories/snapshots/de/spinscale/) it is complaining that the library is missing there.

[ERROR] Failed to execute goal on project procurement-service: Could not resolve dependencies for project edu.sjsu.cmpe:procurement-service:jar:0.0.1-SNAPSHOT: Could not find artifact de.spinscale.dropwizard:dropwizard-jobs:jar:1.0-SNAPSHOT in #sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

Looks like you need to re-upload your jar.

Temporary solution would be to build this jar file and then install it with the following command:

mvn install:install-file -DgroupId=de.spinscale.dropwizard -DartifactId=dropwizard-jobs -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dfile=**/path/to/file**

**Comment by eyalgo** [comment]
hi,
is it released to any public repository?

Thanks !

**Comment by hakandilek** [comment]
@yunspace wanted to do it but we have'nt heard from him for a long time. 

@eyalgo, would you like to take it over?

**Comment by eyalgo** [comment]
Hi,
I would like that.

Please note, I am fairly new with DW.

What are the open issues? Or is it just deploying it?

Thanks !


*Eyal Golan*

Connect

[image: Gmail] <egolan74@gmail.com> [image: LinkedIn]
<http://www.linkedin.com/in/egolan74> [image: My Blog]
<http://eyalgo.com/> [image:
Twitter] <http://twitter.com/eyalgo_egolan> [image: Skype] [image: GitHub]
<https://github.com/eyalgo> [image: Facebook]
<http://www.facebook.com/eyal.golan.14>


P  Save a tree. Please don't print this e-mail unless it's really necessary

**Comment by hakandilek** [comment]
@eyalgo, we've already agreed to release it with the current state. Just remove the "-SNAPSHOT" suffixes and roll it. :-)

**Comment by eyalgo** [comment]
ok.
i'll keep you updated.
should i fork pull request?

*Eyal Golan*

Connect

[image: Gmail] <egolan74@gmail.com> [image: LinkedIn]
<http://www.linkedin.com/in/egolan74> [image: My Blog]
<http://eyalgo.com/> [image:
Twitter] <http://twitter.com/eyalgo_egolan> [image: Skype] [image: GitHub]
<https://github.com/eyalgo> [image: Facebook]
<http://www.facebook.com/eyal.golan.14>


P  Save a tree. Please don't print this e-mail unless it's really necessary

**Comment by hakandilek** [comment]
Would be nice.

**Comment by eyalgo** [comment]
hi,
I did a pull request.
Is there a plan for merging?

thanks,

Eyal

**Comment by hakandilek** [comment]
merged.

**Comment by eyalgo** [comment]
well, it in maven central.
closing the issue.
