### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by meshuga** [spinscale/dropwizard-jobs#13]
Please provide which kind of licence is used in the project.

**Comment by spinscale** [comment]
doh.. we should add that

@hakandilek @simoncurd objects against Apache License? pinging you because you committed code here as well

**Comment by hakandilek** [comment]
Apache License sounds nice. Thanks for asking though.

**Comment by eyalgo** [comment]
added the license. 
please see " add scm element in pom #16 "

**Comment by eyalgo** [comment]
One more thing,
I consulted with http://www.whitesourcesoftware.com/ in regard the license key.
They say it's enough to add it to the POM.

If all agree, let's merge my pull request and I'll deploy to maven repo.

**Comment by hakandilek** [comment]
I do agree.

**Comment by eyalgo** [comment]
great.
can you merge the pull request?
i will then continue from there/

**Comment by spinscale** [comment]
+1... thx so much for doing all the checking!
