### ISSUE TITLE
Add clustering support for jobs running on multiple nodes

### ISSUE THREAD

**Issue by hotmeatballsoup** [spinscale/dropwizard-jobs#17]
A current limitation, from the README, is that jobs scheduled/ran through this lib cannot be clustered and orchestrated across multiple nodes. This is showstopper for jobs that cannot be built for idempotency.

I am suggesting an interface be added to allow jobs to be clustered across multiple nodes, and perhaps provide one concrete implementation of this API to give users right out of the box, perhaps something based on ZooKeeper.

**Comment by hotmeatballsoup** [comment]
Also, I am happy to lead the charge on this, but would like to open a discussion with current maintainers as to what the best approach might be.

**Comment by hakandilek** [comment]
Nobody had reacted to this one over a year. @hotmeatballsoup, do you have an example?

**Comment by plevie** [comment]
Is there any progress or a workaround?

**Comment by spinscale** [comment]
closed by #37 ?
