### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by hotmeatballsoup** [spinscale/dropwizard-jobs#18]
Oracle is EOLing Java 7 [next month](http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates). Creating a ticket and I'll send a pull request for this soon.

**Comment by hakandilek** [comment]
I think we should stay at the lowest version unless we really need to upgrade.
@hotmeatballsoup Do you have any PR to commit requiring Java 8+ language features?

**Comment by spinscale** [comment]
using java8 since upgrading to dropwizard 1.0.2

**Comment by MusikPolice** [comment]
I wonder if that's why the Travis job is failing. It's yaml tries to set Java 1.7 as the test target. Maybe we need to update that file to target 1.8 instead 

---
Jonathan Fritz
On the web: http://www.jonathanfritz.ca
