### ISSUE TITLE
access to database objects from a job: howto?

### ISSUE THREAD

**Issue by ivanmobigis** [spinscale/dropwizard-jobs#26]
Sorry if this is a dumb question, but I'm struggling to see how to get a handle on a DAO or sessionFactory from inside a job. Is this possible, maybe a quick addition to the docs would be nice seeing as it's a pretty basic requirement (i think?)

cheers

-i

**Comment by rizeon** [comment]
You need some kind of inject framework for that or simply initialize static methods to get handles.
One approach is to use guice included in this library, however I would advise to use other guice modules like:
https://github.com/HubSpot/dropwizard-guice
Also take a look at http://modules.dropwizard.io/thirdparty/

**Comment by hakandilek** [comment]
@ivanmobigis I suppose your question is answered. Shall I close the issue?

**Comment by ivanmobigis** [comment]
OK Thanks rizeon,

We managed using a static method on the main Application class that returns the session factory.. it seems to work fine and prevented the need for a whole other component/library in the mix.

There was never an 'issue' associated with this, it was more a how-to request.. anyway it can def. be closed now.

Cheers and thanks,

-ivan

**Comment by hakandilek** [comment]
@ivanmobigis, Thanks for the reply. :+1:
