### ISSUE TITLE
Deploy v1.0.2 to Maven Central

### ISSUE THREAD

**Issue by davidwarshaw** [spinscale/dropwizard-jobs#35]
Great plugin guys! ❤️ 
The latest version in Maven Central is v1.0.1. Any plans to deploy v1.0.2?
https://oss.sonatype.org/content/groups/staging/de/spinscale/dropwizard-jobs/

**Comment by spinscale** [comment]
@hakandilek might make sense before upgrading to 1.0?

**Comment by hakandilek** [comment]
Yes, sure. I currently have limited access through the proxy at my workstation. I'd be glad if someone takes over.

**Comment by OverlyExcessive** [comment]
Any updates on this?

**Comment by spinscale** [comment]
@hakandilek I ran `mvn -Prelease release:prepare` and `mvn -Prelease release:perform` but was only able to create and upload snapshots... our deployment process seems broken. Can you take a look (and sorry for the mess in the commit history)?

Or did you do the upload differently the last time?

**Comment by hakandilek** [comment]
I think @eyalgo was doing the deployments. I can't deploy due to the network restrictions on my workstation.

It might make sense to publish 1.1.4 right away.

**Comment by MusikPolice** [comment]
@hakandilek @spinscale Now that #37 is merged, I'd like to see a deployment as well. Anything I can do to help?

**Comment by spinscale** [comment]
just deployed 1.1.4... we'll fix the useless version numbers soon I would say.. I have a list of other ideas to clean up the code.. some things are rather embarassing IMO

**Comment by davidwarshaw** [comment]
🎉
