### ISSUE TITLE
Deploy v2.0.0 to Maven Central

### ISSUE THREAD

**Issue by hatchy** [spinscale/dropwizard-jobs#39]
Hi,

Great library!

I would like to make use of 2.0.0 but it is not yet available in maven central.

Are there any plans to publish this?

Thanks

**Comment by eyalgo** [comment]
Hi @hatchy  ,
I published the library the last time.

I haven't touched that for a long time :)
If there is no one who can take over, I will try to find time for it.

Cheers,

**Comment by MusikPolice** [comment]
I think @spinscale recently released 1.1.5. 

---
Jonathan Fritz
On the web: http://www.jonathanfritz.ca

**Comment by timja-kainos** [comment]
Any chance 2.0 can be published?

**Comment by spinscale** [comment]
just released 2.0.1 (some day mvn will let me do a release without retrying a bunch of times... but not today)
https://oss.sonatype.org/content/repositories/releases/de/spinscale/dropwizard/
