### ISSUE TITLE
Jobs from configuration 

### ISSUE THREAD

**Issue by gmaturana** [spinscale/dropwizard-jobs#40]
Hi,

I tried to run some jobs from the configuration file and I couldn't get it working.

I think that something is missing in the documentation

Could you please add an example?? thnks

**Comment by danielmelogpi** [comment]
@gmaturana , There is some documentation in the README.md that worked for me 
-  In the Configuration class add the corresponding property:
- Then the @Every annotation can be used without a value, its value is set from the configuration:
```java
@Every("${foobar}")
public class MyJob extends Job {
    ...
}
```

**Comment by danielmelogpi** [comment]
@gmaturana , can you close this one? Was that solved?
