### ISSUE TITLE
Deploy 3.0.0 release

### ISSUE THREAD

**Issue by xargsgrep** [spinscale/dropwizard-jobs#49]
poms have been updated to 3.0.0 but I think only @spinscale has the credentials to be able to do deploy it to the repository.

**Comment by schmitzhermes** [comment]
Hey, it works actually pretty great. It'd be nice if you deploy the 3.0.0 to maven central so we can actually use it w/o mirroring it in our own Nexus etc. pp. 

Thanks a lot in advance!

**Comment by zunzunwang** [comment]
We hope It could be deployed faster. :)

**Comment by spinscale** [comment]
gna, I keep forgetting this, sorry folks. I'll try to do it in the evening...

@xargsgrep if you want to deploy yourself (and you are willing to maintain in the future), why not change the groupId, so you can deploy it or create a group id everyone can deploy under?

**Comment by spinscale** [comment]
3.0.0 deployed.. see https://oss.sonatype.org/content/repositories/releases/de/spinscale/dropwizard/

**Comment by xargsgrep** [comment]
@spinscale I already have a groupId (com.xargsgrep) that I can deploy under going forward but not sure if people would be ok with that?

**Comment by spinscale** [comment]
@xargsgrep most important is, that other contributors can deploy as well... requires some allowance on sonatype if I'm not mistaken?

**Comment by xargsgrep** [comment]
I'm not really sure how it works on sonatype, I'd have to look into that.
