### ISSUE TITLE
Configure quartz persistence via dropwizard

### ISSUE THREAD

**Issue by schmitzhermes** [spinscale/dropwizard-jobs#50]
Hey guys,

I tried `dropwizard-jobs` yesterday and it works pretty well. I have one major concern that I'd like to address, though. 
Although just putting `quartz.properties` in the classpath is an easy way to enable persistence, it sure has its drawbacks. I thought about handling this also via Dropwizards `Configuration`. 

At [https://github.com/spinscale/dropwizard-jobs/blob/master/dropwizard-jobs-core/src/main/java/de/spinscale/dropwizard/jobs/JobManager.java#L50](this) point we tell Dropwizard to look for `quartz.properties`. 
We can, however, provide a `java.util.Properties` at this point and give it `initialize` the `StdSchedulerFactory` (see [http://www.quartz-scheduler.org/api/2.2.1/org/quartz/impl/StdSchedulerFactory.html#initialize(java.util.Properties)](here)). This way we could utilize Dropwizard's Config at this point.

With this in place we could e.g. utilize the same database connection we already have in our app, use Environment-Variables for configuring etc. pp. Moreover it feels more 'dropwizard-ish'.

Any interest in this idea? I'd be happy to provide a PR.

**Comment by MusikPolice** [comment]
Sounds like an excellent idea. Please submit a PR if you have time.

**Comment by schmitzhermes** [comment]
It's already integrated by #51  :-)
